apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1  # 生产环境使用更多副本
  template:
    spec:
      containers:
      - name: frontend-service
        resources:
          limits:
            cpu: "400m"
            memory: "400Mi"
