apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        argocd-image-updater.argoproj.io/image-list: app=crpi-mc95723p4ndmj8y3.cn-chengdu.personal.cr.aliyuncs.com/product_123/frontend-service
        argocd-image-updater.argoproj.io/app.update-strategy: latest
    spec:
      containers:
        - name: frontend
          image: crpi-mc95723p4ndmj8y3.cn-chengdu.personal.cr.aliyuncs.com/product_123/frontend-service:latest
          ports:
            - containerPort: 80
              name: frontend
          resources:
            requests:
              cpu: 200m
              memory: 160Mi
            limits:
              cpu: 400m
              memory: 360Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 3
      imagePullSecrets:
        - name: aliyun-acr-secret

